// versi

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DataVortex | PT Netra Vidya Analitika",
  description: "Executive Analytics System for Adidas Indonesia",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0a0a0a] text-white`}
      >
        <TooltipProvider>
          {children}
          <Toaster position="top-center" richColors />
        </TooltipProvider>
      </body>
    </html>
  );
}

//  versi

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// // menambahkan untuk memanggil semua "alat" yang sudah kamu install tadi.
// import { TooltipProvider } from "@/components/ui/tooltip"; //
// import { Toaster } from "@/components/ui/sonner"; //

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // ------------------------------------------------------------------------------------------------

// // yang baru ai versi 2
// export const metadata: Metadata = {
//   // title: "Create Next App", default awal
//   // yang baru
//   title: "DataVortex - PT Netra Vidya Analitika",
//   // description: "Generated by create next app", default awal
//   // yang baru
//   description: "Sistem Analisis Penjualan Adidas Indonesia",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         // TAMBAHKAN 'dark' di akhir baris ini agar mode gelap aktif
//         className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
//       >
//         <TooltipProvider>
//           {children}
//           <Toaster position="top-center" richColors />
//         </TooltipProvider>
//       </body>
//     </html>
//   );
// }

// ------------------------------------------------------------------------------------------------

// //YANG  export default function RootLayout VERSI AI 1
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* TooltipProvider wajib membungkus children agar Sidebar tidak error */}
//         <TooltipProvider>
//           {children}
//           {/* Toaster diletakkan di sini agar bisa muncul di semua halaman */}
//           <Toaster position="top-center" richColors />
//         </TooltipProvider>
//       </body>
//     </html>
//   );
// }

// default awal nya
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// -----------------------------------------------------------------------
// catatan buat belajar

// dari AI BUAT NGOREKSI
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { TooltipProvider } from "@/components/ui/tooltip"; //
// import { Toaster } from "@/components/ui/sonner"; //

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "DataVortex - PT Netra Vidya Analitika", //
//   description: "Sistem Analisis Penjualan Adidas Indonesia", //
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* TooltipProvider wajib membungkus children agar Sidebar tidak error */}
//         <TooltipProvider>
//           {children}
//           {/* Toaster diletakkan di sini agar bisa muncul di semua halaman */}
//           <Toaster position="top-center" richColors />
//         </TooltipProvider>
//       </body>
//     </html>
//   );
// }
